### ISSUE TITLE
Add the co-sign component to storybook

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-sdk#309]
We currently don't have all formio components hooked up to storybook, which excludes them from visual regression testing.

1. Add a story for the co-sign component in `src/formio/components/Cosign.stories.js`
2. Check the backend form designer for the required JSON for this component
3. Configure/document the story similarly to the other formio components
4. ~~Set up the/a mock endpoint to be called by the co sign component~~

This is about the "new" Co sign, we will not be documenting the `CoSignOld` component.

**Comment by SilviaAmAm** [comment]
@sergei-maertens I don't think that step 4 is needed for the new co-sign? Because it is practically just an email field in the SDK

**Comment by sergei-maertens** [comment]
> @sergei-maertens I don't think that step 4 is needed for the new co-sign? Because it is practically just an email field in the SDK

Yes, I created this ticket back when we only had the old cosign! Step 4 is not needed anymore.
