### ISSUE TITLE
Use description per option in selectboxes and radio components

### ISSUE THREAD

**Issue by SilviaAmAm** [open-formulieren/open-forms-sdk#483]
DH Taiga issue 540

This should happen both in the native components and the formio templates.

![image](https://github.com/open-formulieren/open-forms-sdk/assets/96970/70bb0228-bb9e-49d2-96e8-8472aaaec286)

**Comment by sergei-maertens** [comment]
I don't think this is currently possible in the backend because options only allow specifying label + value and there's no input now for additional descriptions.

**Comment by joeribekker** [comment]
![image](https://github.com/open-formulieren/open-forms-sdk/assets/96970/819304c2-feb1-4b64-aa89-7e9eb0035801)

https://www.figma.com/file/shhwGcqPLi2CapK0P1zz8O/NLDS---Voorbeeld---Bibliotheek?type=design&node-id=1039-2941&mode=design

**Comment by nikkiysendoorn1** [comment]
I finished this in the frontend. There should be an extra description field in the admin.

**Comment by sergei-maertens** [comment]
Specified a bit more in detail what needs to happen in the different repositories:

- In the https://github.com/open-formulieren/types repository:
    - [ ] add the `description` property to the `Option` interface so that the formio builder and future formio renderer know that this property exists. 
    - [ ] ensure that this property is marked as translatable at the type level (`option.openForms.translations.description` should be allowed, same as `option.openForms.translations.label`)
- In the https://github.com/open-formulieren/formio-builder repository:
    - [ ] Ensure that for radio/checkbox components the description can be entered by form designers (currently you can only enter value and label)
    - [ ] Ensure that the translations for the description field can be entered on the translation tab
- In the https://github.com/open-formulieren/open-forms-sdk repository:
    - [ ] Update the checkbox/radio EJS formio templates to make sure the descriptions are displayed
    - [ ] Ensure that the correct NL Design System class names and markup are used
    - [ ] Update the React component for radio too (which is separate from the formio component) with the same constraints as above

Backend:

- Ensure that the description of the option is localized with the active language
