### ISSUE TITLE
Message of `LabelContent` shouldn't rely on `requiredFieldsWithAsterisk`

### ISSUE THREAD

**Issue by Viicos** [open-formulieren/open-forms-sdk#613]
The current definition:

https://github.com/open-formulieren/open-forms-sdk/blob/b1210cd7ed9d2415d2554798bd617d8aad1fed92/src/components/forms/Label.js#L12-L28

uses `requiredFieldsWithAsterisk` to determine if _not required_ should be appended to the label. I think it makes more sense to only rely on `isRequired`.

**Comment by sergei-maertens** [comment]
Discussed, there was a lack in understanding of this configuration parameter :-)
