### ISSUE TITLE
Map: translation "Dichtsbijzijndste" not right and not B1 level. 

### ISSUE THREAD

**Issue by LaurensBurger** [open-formulieren/open-forms-sdk#619]
![image](https://github.com/open-formulieren/open-forms-sdk/assets/112621537/bd4b6981-ff87-4a3c-b47a-af341d4ee4fb)

suggested text: "Adres in de buurt"

**Comment by sergei-maertens** [comment]
@LaurensBurger "Adres in de buurt" or "Meest nabije adres"?
