### ISSUE TITLE
Fix DOMException related to caret restore function (Formio bug)

### ISSUE THREAD

**Issue by sergei-maertens** [open-formulieren/open-forms-sdk#79]
```
DOMException: Failed to execute 'setSelectionRange' on 'HTMLInputElement': The input element's type ('email') does not support selection.
```

This happens in the `Component.restoreCaretPosition` method on Formio 4.12. It appears to be fixed in 4.13: https://github.com/formio/formio.js/blob/4.13.x/src/components/_classes/component/Component.js#L1564

This is currently causing the subsequent logic checks to fail (when the element is focused).

Preferred mitigation: upgrade to Formio 4.13, however we have run into other issues while trying that with the file upload mimetypes. Alternative solution is monkey-patching the method, as the `Component` is base class for a lot of components and simply replacing it with our own subclass will not suffice.

**Comment by SilviaAmAm** [comment]
Note: I can reproduce this error in Chrome, but in Firefox I get this other error:
`Uncaught (in promise) DOMException: An attempt was made to use an object that is not, or is no longer, usable`

This seems to happen in the formStep component:
src/components/FormStep.js:145
```
  142 | // definition by using the ref to the underlying Formio instance.
  143 | // NOTE that this does effectively bring our state.configuration out of sync
  144 | // with the actual form configuration (!).
> 145 | formInstance.setForm(step.formStep.configuration);
      | ^  146 | // the reminder of the state updates we let the reducer handle
  147 | dispatch({
  148 |   type: 'LOGIC_CHECK_DONE',
```
